// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVyY4Wb1oe84bqJaxEGJ6lFrcI4Imy4Fs',
    appId: '1:889428493541:web:5a952eb19fe539ba40800c',
    messagingSenderId: '889428493541',
    projectId: 'mouseirl',
    authDomain: 'mouseirl.firebaseapp.com',
    databaseURL: 'https://mouseirl-default-rtdb.firebaseio.com',
    storageBucket: 'mouseirl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsQif9VHw9DMatUm_LsUfkm7WriACskag',
    appId: '1:889428493541:android:0b68245c1680cc8540800c',
    messagingSenderId: '889428493541',
    projectId: 'mouseirl',
    databaseURL: 'https://mouseirl-default-rtdb.firebaseio.com',
    storageBucket: 'mouseirl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXDU1tE_uuH0WhMLak063UCKszaSywz3g',
    appId: '1:889428493541:ios:42d5693e1cdacf0e40800c',
    messagingSenderId: '889428493541',
    projectId: 'mouseirl',
    databaseURL: 'https://mouseirl-default-rtdb.firebaseio.com',
    storageBucket: 'mouseirl.appspot.com',
    androidClientId:
        '889428493541-n5nbn1kurnjrrvjaku4sc819sjudvg0f.apps.googleusercontent.com',
    iosClientId:
        '889428493541-u1klj81gn9ak6u6j17b4rdbo4mjccgcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.mouseIrlWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXDU1tE_uuH0WhMLak063UCKszaSywz3g',
    appId: '1:889428493541:ios:8499711c43a117e840800c',
    messagingSenderId: '889428493541',
    projectId: 'mouseirl',
    databaseURL: 'https://mouseirl-default-rtdb.firebaseio.com',
    storageBucket: 'mouseirl.appspot.com',
    androidClientId:
        '889428493541-n5nbn1kurnjrrvjaku4sc819sjudvg0f.apps.googleusercontent.com',
    iosClientId:
        '889428493541-fv26l3lj19igtnon0imh3d6a5aoioetf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mouseIrlWebsite.RunnerTests',
  );
}
