// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4eTq-vIaECHUyBq2aAz2HfpQxbLvyx8g',
    appId: '1:694809189982:web:ea656e92f352a5ca101ecf',
    messagingSenderId: '694809189982',
    projectId: 'mouseirlwebsitefirebase',
    authDomain: 'mouseirlwebsitefirebase.firebaseapp.com',
    storageBucket: 'mouseirlwebsitefirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD66SeccJ2ZBYlFDYrkpmvLMwBVO1KrTw',
    appId: '1:694809189982:android:c1026f97f9ff4b99101ecf',
    messagingSenderId: '694809189982',
    projectId: 'mouseirlwebsitefirebase',
    storageBucket: 'mouseirlwebsitefirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF8e1o-RG2HhMF28hylKfcHHLNrg1QMyE',
    appId: '1:694809189982:ios:acc933b827d3bbb6101ecf',
    messagingSenderId: '694809189982',
    projectId: 'mouseirlwebsitefirebase',
    storageBucket: 'mouseirlwebsitefirebase.appspot.com',
    iosClientId: '694809189982-qer16idkoq0i3a4303jvvuv98g394jrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mouseIrlWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF8e1o-RG2HhMF28hylKfcHHLNrg1QMyE',
    appId: '1:694809189982:ios:cc78d570fb57d0cb101ecf',
    messagingSenderId: '694809189982',
    projectId: 'mouseirlwebsitefirebase',
    storageBucket: 'mouseirlwebsitefirebase.appspot.com',
    iosClientId: '694809189982-f4kb9s4p0eaq2337b3au54m26gbr454t.apps.googleusercontent.com',
    iosBundleId: 'com.example.mouseIrlWebsite.RunnerTests',
  );
}
